version: "3.3"

services:
  app:
    build: .

    ports:
      - "5050:5050"

    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:54321/postgres?sslmode=disable

    depends_on:
      - db
    
    db:
      build: ./database